spring.application.name=springboot

# Import .env file
spring.config.import=optional:file:.env[.properties]

# JPA
spring.jpa.database=postgresql
spring.jpa.hibernate.ddl-auto=create

# Database
spring.datasource.hikari.maximum-pool-size=4
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

# API KEY
gpt.api.key=${GPT_API_KEY}
gpt.api.model=${GPT_API_MODEL}

# JWT Security Key
security.jwt.key=${JWT_KEY}
security.jwt.expire-time=${JWT_EXPIRE_TIME}

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html

springdoc.api-docs.path=/api-docs

springdoc.default-consumes-media-type=application/json
springdoc.default-produces-media-type=application/json

springdoc.swagger-ui.operations-sorter=alpha
springdoc.swagger-ui.tags-sorter=alpha

springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.swagger-ui.doc-expansion=none
